#!/bin/bash --login

if [ ! $1 ]; then
    echo "usage: $0 <path to local svn project checkout>"
    echo "        deployment server setzen: svn propset svn2ftp_server 'ftp://<user>:<passwort>@<server>/<path>' ."
    exit 1
fi


# set up nice names for the incoming parameters to make the script more readable
project_directory=$1
deploy_directory=$project_directory/deploy
target_directory=$deploy_directory/tmp$$
pushd $project_directory
mkdir -p $deploy_directory
repository=`svn info | grep "URL:" | cut -d ' ' -f 2`
deploy_server=`svn propget svn2ftp_server .`

deploy_type=`expr "$deploy_server" : 's\{0,1\}\(ftp\)'`

if [ "$deploy_type" != "ftp" ]; then
    echo "ERROR: unsuported deployment target ($deploy_server)! Only ftp/sftp are supported"
    exit 2
fi

# if revision_from is not already set, get it from the .revision file if it exists
if [ ! $revision_from ] && [ -f $deploy_directory/revision ]; then
    revision_from=`cat $deploy_directory/revision`
fi

# now either get it from a specific revision, or everything
if [ $revision_from ]; then

    # the grep is needed so we only get added/modified files and not the deleted ones or anything else
    # if it's a modified directory it's " M" so won't show with this command (good)
    # if it's an added directory it's still "A" so will show with this command (not so good)

    for line in `svn diff --summarize -r$revision_from:HEAD $repository | grep "^[AM]"`
    do
        # each line in the above command in the for loop is split into two:
        # 1) the status line (containing A, M, AM, D etc)
        # 2) the full repository and filename string
        # so only export the file when it's not the status line
        if [ $line != "A" ] && [ $line != "AM" ] && [ $line != "M" ]; then
            # use sed to remove the repository from the full repo and filename
            filename=`echo "$line" |sed "s|$repository||g"`
            # don't export if it's a directory we've already created
            if [ ! -d $target_directory$filename ]; then
                directory=`dirname $filename`
                mkdir -p $target_directory$directory
                svn export $line $target_directory$filename
                if [ $deploy_type == "ftp" ] && [ ! -d $target_directory$filename ]; then
                    curl --silent --ftp-create-dirs -T $target_directory$filename $deploy_server$filename
                fi
            fi
        fi
    done

    # to summarize any deleted files or directories at the end of the script uncomment the following line
    #svn diff --summarize -r$revision_from:HEAD $repository | grep "^[D]"

else

    svn export --force $repository $target_directory

fi

# get the current revision and write to .revision file
echo `svn info $repository | grep ^Revision | sed 's/Revision: *//'` > $deploy_directory/revision
if [ $deploy_type == "ftp" ]; then
    curl --silent --ftp-create-dirs -T $deploy_directory/revision $deploy_server/deploy/revision
fi

popd

